### ISSUE TITLE
Newbie issues

### ISSUE THREAD

**Issue by InTransit112** [arduino-libraries/Arduino_Threads#102]
When trying to open and run the "shared counter" example, I can never get the arduino IDE to open the .inot file type and so the compiler always throws an error when calling producer()/consumer(). Any words of wisdom to trickle down?

```
C:\Users\jgold\AppData\Local\Temp\.arduinoIDE-unsaved2024129-28668-1l8kexo.higr\Shared_Counter\Shared_Counter.ino: In function 'void setup()':
C:\Users\jgold\AppData\Local\Temp\.arduinoIDE-unsaved2024129-28668-1l8kexo.higr\Shared_Counter\Shared_Counter.ino:8:3: error: 'Producer' was not declared in this scope
   Producer.start();
   ^~~~~~~~
C:\Users\jgold\AppData\Local\Temp\.arduinoIDE-unsaved2024129-28668-1l8kexo.higr\Shared_Counter\Shared_Counter.ino:8:3: note: suggested alternative: 'prog_uchar'
   Producer.start();
   ^~~~~~~~
   prog_uchar
C:\Users\jgold\AppData\Local\Temp\.arduinoIDE-unsaved2024129-28668-1l8kexo.higr\Shared_Counter\Shared_Counter.ino:9:3: error: 'Consumer' was not declared in this scope
   Consumer.start();
   ^~~~~~~~

exit status 1

Compilation error: 'Producer' was not declared in this scope


```

**Comment by AustinCast** [comment]
I am experiencing the same issue, even when compiling the "shared counter" example in Arduino CLI.

**Comment by aentinger** [comment]
Hi @InTransit112 and @AustinCast :coffee: :wave:

The issues you are experiencing stem from the fact that this library requires a specially build version of `arduino-cli` in order to work. You can download it as well as find further information [here](https://github.com/arduino-libraries/Arduino_Threads/blob/main/docs/README.md).

There is also no support for inot-files in the Arduino IDE - this library is currently in [beta](https://github.com/arduino-libraries/Arduino_Threads/tree/main#zap-caveats)  mode, as advertised by its README.
